#!/usr/bin/env bash

set -euo pipefail

DSV4_FLASH_SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=${REPO_ROOT:-$(cd -- "${DSV4_FLASH_SCRIPT_DIR}/../.." && pwd)}

export PYTHON=${PYTHON:-/usr/local/python3.12.13/bin/python}
VLLM_CLI=${VLLM_CLI:-vllm}
export PYTHON_VLLM_PATH=${PYTHON_VLLM_PATH:-/vllm-workspace/vllm}
export PYTHON_VLLM_ASCEND_PATH=${PYTHON_VLLM_ASCEND_PATH:-/vllm-workspace/vllm-ascend}
export PYTHON_AFD_PLUGIN_PATH=${PYTHON_AFD_PLUGIN_PATH:-${REPO_ROOT}/afd-plugin26}
export PYTHONPATH="${PYTHON_AFD_PLUGIN_PATH}:${PYTHON_VLLM_ASCEND_PATH}:${PYTHON_VLLM_PATH}:${PYTHONPATH:-}"

export VLLM_USE_V1=${VLLM_USE_V1:-1}
export VLLM_WORKER_MULTIPROC_METHOD=${VLLM_WORKER_MULTIPROC_METHOD:-spawn}
export AFD_FORCE_SPAWN_MULTIPROCESSING=${AFD_FORCE_SPAWN_MULTIPROCESSING:-1}

DSV4_MODEL=${DSV4_MODEL:-/home/admin/model-csi/models/modelhub_51300042_deepseek-v4-flash-w8a8-mtp-126600065_20260527131010/model}
SERVED_MODEL_NAME=${SERVED_MODEL_NAME:-dsv4}

# P_NODE_IP is both the P-side communication address and the CamAsync
# rendezvous address. It must be reachable from the D node and all P ranks.
# P_NODE_IP is the primary prefill node, vLLM DP coordinator, and default AFD
# rendezvous host. P_SECONDARY_NODE_IP is required by the two-node benchmark
# topologies. LOCAL_NODE_IP is derived from PREFILL_NODE_ID unless explicitly
# overridden.
P_NODE_IP=${P_NODE_IP:-}
P_SECONDARY_NODE_IP=${P_SECONDARY_NODE_IP:-}
D_NODE_IP=${D_NODE_IP:-}
NIC_NAME=${NIC_NAME:-}
VLLM_HOST=${VLLM_HOST:-0.0.0.0}
PROXY_HOST=${PROXY_HOST:-0.0.0.0}

PREFILL_PORT=${PREFILL_PORT:-7100}
FFN_PORT=${FFN_PORT:-7101}
DECODE_PORT=${DECODE_PORT:-7100}
PROXY_PORT=${PROXY_PORT:-8000}
AFD_PORT=${AFD_PORT:-1239}
AFD_HOST=${AFD_HOST:-${P_NODE_IP}}
PREFILL_DP_RPC_PORT=${PREFILL_DP_RPC_PORT:-12321}
DECODE_DP_RPC_PORT=${DECODE_DP_RPC_PORT:-12321}
PD_KV_PREFILL_PORT=${PD_KV_PREFILL_PORT:-30000}
PD_KV_DECODE_PORT=${PD_KV_DECODE_PORT:-30100}

# AFD benchmark layouts use two 16-NPU 910C nodes. Node 0 owns 16 Attention
# ranks; node 1 owns the remaining 8 Attention ranks and all 8 FFN ranks.
# Keep "legacy" for the original single-node DP2TP4 + EP8 layout.
PREFILL_TOPOLOGY=${PREFILL_TOPOLOGY:-legacy}
PREFILL_NODE_ID=${PREFILL_NODE_ID:-0}
case "${PREFILL_TOPOLOGY}" in
  afd_dp6tp4)
    PREFILL_DP_SIZE=${PREFILL_DP_SIZE:-6}
    PREFILL_TP_SIZE=${PREFILL_TP_SIZE:-4}
    NUM_ATTENTION_RANKS=${NUM_ATTENTION_RANKS:-24}
    ATTN_RANKS_PER_DP=${ATTN_RANKS_PER_DP:-4}
    ;;
  afd_dp3tp8)
    PREFILL_DP_SIZE=${PREFILL_DP_SIZE:-3}
    PREFILL_TP_SIZE=${PREFILL_TP_SIZE:-8}
    NUM_ATTENTION_RANKS=${NUM_ATTENTION_RANKS:-24}
    ATTN_RANKS_PER_DP=${ATTN_RANKS_PER_DP:-8}
    ;;
  afd_dp4tp2)
    # Single-node AFD layout: Attention DP4xTP2 on devices 0-7 and
    # FFN TP1/EP8 on devices 8-15.
    PREFILL_DP_SIZE=${PREFILL_DP_SIZE:-4}
    PREFILL_TP_SIZE=${PREFILL_TP_SIZE:-2}
    NUM_ATTENTION_RANKS=${NUM_ATTENTION_RANKS:-8}
    ATTN_RANKS_PER_DP=${ATTN_RANKS_PER_DP:-2}
    ;;
  legacy)
    PREFILL_DP_SIZE=${PREFILL_DP_SIZE:-2}
    PREFILL_TP_SIZE=${PREFILL_TP_SIZE:-4}
    NUM_ATTENTION_RANKS=${NUM_ATTENTION_RANKS:-8}
    ATTN_RANKS_PER_DP=${ATTN_RANKS_PER_DP:-4}
    ;;
  ep16 | ep16_dp4tp4 | ep16_dp8tp2 | ep16_dp2tp8 | ep32)
    # Full-model EP launchers resolve their own DP-local layout.
    PREFILL_DP_SIZE=${PREFILL_DP_SIZE:-1}
    PREFILL_TP_SIZE=${PREFILL_TP_SIZE:-1}
    NUM_ATTENTION_RANKS=${NUM_ATTENTION_RANKS:-1}
    ATTN_RANKS_PER_DP=${ATTN_RANKS_PER_DP:-1}
    ;;
  *)
    echo "Unknown PREFILL_TOPOLOGY=${PREFILL_TOPOLOGY}" >&2
    return 2 2>/dev/null || exit 2
    ;;
esac

FFN_DP_SIZE=${FFN_DP_SIZE:-8}
NUM_FFN_RANKS=${NUM_FFN_RANKS:-8}

case "${PREFILL_NODE_ID}" in
  0)
    LOCAL_NODE_IP=${LOCAL_NODE_IP:-${P_NODE_IP}}
    PREFILL_DP_START_RANK=${PREFILL_DP_START_RANK:-0}
    PREFILL_HEADLESS=${PREFILL_HEADLESS:-0}
    ;;
  1)
    LOCAL_NODE_IP=${LOCAL_NODE_IP:-${P_SECONDARY_NODE_IP}}
    PREFILL_HEADLESS=${PREFILL_HEADLESS:-1}
    ;;
  *)
    echo "PREFILL_NODE_ID must be 0 or 1" >&2
    return 2 2>/dev/null || exit 2
    ;;
esac

case "${PREFILL_TOPOLOGY}:${PREFILL_NODE_ID}" in
  afd_dp6tp4:0)
    PREFILL_START_FFN=${PREFILL_START_FFN:-0}
    PREFILL_DP_SIZE_LOCAL=${PREFILL_DP_SIZE_LOCAL:-4}
    PREFILL_ATTN_VISIBLE_DEVICES=${PREFILL_ATTN_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15}
    ;;
  afd_dp6tp4:1)
    PREFILL_START_FFN=${PREFILL_START_FFN:-1}
    PREFILL_DP_SIZE_LOCAL=${PREFILL_DP_SIZE_LOCAL:-2}
    PREFILL_DP_START_RANK=${PREFILL_DP_START_RANK:-4}
    PREFILL_ATTN_VISIBLE_DEVICES=${PREFILL_ATTN_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}
    ;;
  afd_dp3tp8:0)
    PREFILL_START_FFN=${PREFILL_START_FFN:-0}
    PREFILL_DP_SIZE_LOCAL=${PREFILL_DP_SIZE_LOCAL:-2}
    PREFILL_ATTN_VISIBLE_DEVICES=${PREFILL_ATTN_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15}
    ;;
  afd_dp3tp8:1)
    PREFILL_START_FFN=${PREFILL_START_FFN:-1}
    PREFILL_DP_SIZE_LOCAL=${PREFILL_DP_SIZE_LOCAL:-1}
    PREFILL_DP_START_RANK=${PREFILL_DP_START_RANK:-2}
    PREFILL_ATTN_VISIBLE_DEVICES=${PREFILL_ATTN_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}
    ;;
  afd_dp4tp2:0)
    PREFILL_START_FFN=${PREFILL_START_FFN:-1}
    PREFILL_DP_SIZE_LOCAL=${PREFILL_DP_SIZE_LOCAL:-4}
    PREFILL_ATTN_VISIBLE_DEVICES=${PREFILL_ATTN_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}
    ;;
  afd_dp4tp2:1)
    echo "afd_dp4tp2 is a single-node topology; launch only PREFILL_NODE_ID=0" >&2
    return 2 2>/dev/null || exit 2
    ;;
  *)
    PREFILL_DP_SIZE_LOCAL=${PREFILL_DP_SIZE_LOCAL:-}
    PREFILL_ATTN_VISIBLE_DEVICES=${PREFILL_ATTN_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}
    PREFILL_START_FFN=${PREFILL_START_FFN:-1}
    ;;
esac
PREFILL_FFN_VISIBLE_DEVICES=${PREFILL_FFN_VISIBLE_DEVICES:-8,9,10,11,12,13,14,15}
PREFILL_ENABLE_KV_CONNECTOR=${PREFILL_ENABLE_KV_CONNECTOR:-0}

# The D topology follows the vllm-ascend DSV4 Flash 910C PD example.
DECODE_DP_SIZE=${DECODE_DP_SIZE:-16}
DECODE_TP_SIZE=${DECODE_TP_SIZE:-1}
DECODE_VISIBLE_DEVICES=${DECODE_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15}

case "${PREFILL_TOPOLOGY}" in
  afd_dp6tp4 | afd_dp3tp8 | afd_dp4tp2 | ep16 | ep16_dp4tp4 | ep16_dp8tp2 | ep16_dp2tp8 | ep32) DEFAULT_MAX_MODEL_LEN=65536 ;;
  *) DEFAULT_MAX_MODEL_LEN=1048576 ;;
esac
MAX_MODEL_LEN=${MAX_MODEL_LEN:-${DEFAULT_MAX_MODEL_LEN}}
PREFILL_MAX_NUM_BATCHED_TOKENS=${PREFILL_MAX_NUM_BATCHED_TOKENS:-8192}
DECODE_MAX_NUM_BATCHED_TOKENS=${DECODE_MAX_NUM_BATCHED_TOKENS:-120}
PREFILL_MAX_NUM_SEQS=${PREFILL_MAX_NUM_SEQS:-16}
FFN_MAX_NUM_SEQS=${FFN_MAX_NUM_SEQS:-16}
DECODE_MAX_NUM_SEQS=${DECODE_MAX_NUM_SEQS:-60}
BLOCK_SIZE=${BLOCK_SIZE:-128}
PREFILL_GPU_MEMORY_UTILIZATION=${PREFILL_GPU_MEMORY_UTILIZATION:-0.7}
DECODE_GPU_MEMORY_UTILIZATION=${DECODE_GPU_MEMORY_UTILIZATION:-0.9}
MODEL_LOADER_THREADS=${MODEL_LOADER_THREADS:-128}

export HCCL_BUFFSIZE=${HCCL_BUFFSIZE:-4096}
PREFILL_HCCL_BUFFSIZE=4096
export HCCL_OP_EXPANSION_MODE=${HCCL_OP_EXPANSION_MODE:-AIV}
export HCCL_CONNECT_TIMEOUT=${HCCL_CONNECT_TIMEOUT:-1200}
export HCCL_EXEC_TIMEOUT=${HCCL_EXEC_TIMEOUT:-2000}
export VLLM_RPC_TIMEOUT=${VLLM_RPC_TIMEOUT:-3600000}
export VLLM_EXECUTE_MODEL_TIMEOUT_SECONDS=${VLLM_EXECUTE_MODEL_TIMEOUT_SECONDS:-30000}
export OMP_PROC_BIND=${OMP_PROC_BIND:-false}
export OMP_NUM_THREADS=${OMP_NUM_THREADS:-10}
export PYTORCH_NPU_ALLOC_CONF=${PYTORCH_NPU_ALLOC_CONF:-expandable_segments:True}
export TASK_QUEUE_ENABLE=${TASK_QUEUE_ENABLE:-1}
export AFD_FORCE_BALANCED_TOPK_IDS=${AFD_FORCE_BALANCED_TOPK_IDS:-0}
export AFD_CAM_OP_IO_LOG=${AFD_CAM_OP_IO_LOG:-0}
export AFD_ASYNC_MOE_LAYOUT_LOG=${AFD_ASYNC_MOE_LAYOUT_LOG:-0}

CANN_ROOT=${CANN_ROOT:-/usr/local/Ascend/cann-9.0.1}
case "${PREFILL_TOPOLOGY}" in
ep16 | ep16_dp4tp4 | ep16_dp8tp2 | ep16_dp2tp8 | ep32)
  ;;
*)
  CAM_VENDOR=${CAM_VENDOR:-${CANN_ROOT}/opp/vendors/CAM}
  CAM_OPAPI_DIR=${CAM_OPAPI_DIR:-${CAM_VENDOR}/op_api/lib}
  CAM_OPAPI=${CAM_OPAPI:-${CAM_OPAPI_DIR}/libopapi.so}
  export ASCEND_CUSTOM_OPP_PATH="${CAM_VENDOR}:${ASCEND_CUSTOM_OPP_PATH:-}"
  export CAM_CUST_OPAPI_LIB_PATH=${CAM_CUST_OPAPI_LIB_PATH:-${CAM_OPAPI}}
  export LD_LIBRARY_PATH="${CAM_OPAPI_DIR}:${CAM_VENDOR}/op_api:${LD_LIBRARY_PATH:-}"
  if [[ -f "${CAM_OPAPI}" ]]; then
    export LD_PRELOAD="${CAM_OPAPI}${LD_PRELOAD:+:${LD_PRELOAD}}"
  fi
  ;;
esac

LOG_DIR=${LOG_DIR:-${DSV4_FLASH_SCRIPT_DIR}/logs}
PID_DIR=${PID_DIR:-${LOG_DIR}/pids}
mkdir -p "${LOG_DIR}" "${PID_DIR}"

require_common_network() {
  : "${P_NODE_IP:?Set P_NODE_IP to the P node communication IP}"
  : "${D_NODE_IP:?Set D_NODE_IP to the D node communication IP}"
  : "${NIC_NAME:?Set NIC_NAME to the HCCL/Gloo network interface}"
}

require_prefill_network() {
  : "${P_NODE_IP:?Set P_NODE_IP to the primary P node communication IP}"
  : "${LOCAL_NODE_IP:?Set LOCAL_NODE_IP or the node IP for PREFILL_NODE_ID}"
  : "${NIC_NAME:?Set NIC_NAME to the HCCL/Gloo network interface}"
  if [[ "${PREFILL_ENABLE_KV_CONNECTOR}" == 1 ]]; then
    : "${D_NODE_IP:?Set D_NODE_IP when PREFILL_ENABLE_KV_CONNECTOR=1}"
  fi
}

configure_network() {
  local local_ip=$1
  export HCCL_IF_IP="${local_ip}"
  export HCCL_SOCKET_IFNAME="${NIC_NAME}"
  export GLOO_SOCKET_IFNAME="${NIC_NAME}"
  export TP_SOCKET_IFNAME="${NIC_NAME}"
}

validate_topology() {
  case "${PREFILL_MAX_NUM_BATCHED_TOKENS}" in
    4096 | 8192 | 16384 | 32768 | 65536) ;;
    *)
      echo "PREFILL_MAX_NUM_BATCHED_TOKENS must be one of 4096, 8192, 16384, 32768, 65536" >&2
      return 1
      ;;
  esac
  if (( PREFILL_DP_SIZE * PREFILL_TP_SIZE != NUM_ATTENTION_RANKS )); then
    echo "PREFILL_DP_SIZE * PREFILL_TP_SIZE must equal NUM_ATTENTION_RANKS" >&2
    return 1
  fi
  if (( FFN_DP_SIZE != NUM_FFN_RANKS )); then
    echo "FFN_DP_SIZE must equal NUM_FFN_RANKS for TP1/EP FFN" >&2
    return 1
  fi
  if (( PREFILL_TP_SIZE != ATTN_RANKS_PER_DP )); then
    echo "PREFILL_TP_SIZE must equal ATTN_RANKS_PER_DP" >&2
    return 1
  fi
  if [[ -n "${PREFILL_DP_SIZE_LOCAL}" ]] &&
    (( PREFILL_DP_START_RANK + PREFILL_DP_SIZE_LOCAL > PREFILL_DP_SIZE )); then
    echo "PREFILL_DP_START_RANK + PREFILL_DP_SIZE_LOCAL exceeds global PREFILL_DP_SIZE" >&2
    return 1
  fi
}
